#!/usr/bin/env zsh
# Installer/Updater for msfvenom zsh autocomplete
# Save as install-msfvenom-completion_zsh.sh and run with:
# sudo zsh install-msfvenom-completion_zsh.sh

INSTALL_PATH="/usr/share/zsh/site-functions/_msfvenom"
CACHE_DIR="/var/cache/msfvenom_completion"
PAYLOADS="$CACHE_DIR/payloads.txt"
ENCODERS="$CACHE_DIR/encoders.txt"
FORMATS="$CACHE_DIR/formats.txt"
PLATFORMS="$CACHE_DIR/platforms.txt"
ARCHS="$CACHE_DIR/archs.txt"
OPTIONS="$CACHE_DIR/options.txt"

_build_cache() {
  mkdir -p "$CACHE_DIR"
  # generate lists, ignore errors if msfvenom missing
  msfvenom -l payloads 2>/dev/null | awk '{print $1}' | grep '/' >| "$PAYLOADS" 2>/dev/null || true
  msfvenom -l encoders 2>/dev/null | awk '{print $1}' >| "$ENCODERS" 2>/dev/null || true
  msfvenom -l formats 2>/dev/null | awk '{print $1}' >| "$FORMATS" 2>/dev/null || true
  msfvenom --list platforms 2>/dev/null | awk 'NR>1 {print $1}' >| "$PLATFORMS" 2>/dev/null || true
  msfvenom --list archs 2>/dev/null | awk 'NR>1 {print $1}' >| "$ARCHS" 2>/dev/null || true
  cat >| "$OPTIONS" <<'EOL'
-p
-f
-e
-h
-l
--list
--platform
--arch
--payload-options
--help
LHOST
LPORT
lhost
lport
EOL
}

_init_cache() {
  for f in "$PAYLOADS" "$ENCODERS" "$FORMATS" "$PLATFORMS" "$ARCHS" "$OPTIONS"; do
    if [[ ! -s "$f" ]]; then
      _build_cache
      break
    fi
  done
}

# ensure destination dir exists before writing
mkdir -p "$(dirname "$INSTALL_PATH")"

# write the zsh completion file with embedded static variable defs
cat >| "$INSTALL_PATH" <<'EOF'
#compdef msfvenom
# msfvenom zsh completion generated by installer
CACHE_DIR="/var/cache/msfvenom_completion"
PAYLOADS="$CACHE_DIR/payloads.txt"
ENCODERS="$CACHE_DIR/encoders.txt"
FORMATS="$CACHE_DIR/formats.txt"
PLATFORMS="$CACHE_DIR/platforms.txt"
ARCHS="$CACHE_DIR/archs.txt"
OPTIONS="$CACHE_DIR/options.txt"

_msfvenom_completion() {
  typeset -A opt_args
  local -a expl
  local cur prev
  cur=${words[CURRENT]}
  prev=${words[CURRENT-1]}

  if [[ $prev == "-p" ]]; then
    if [[ -s "$PAYLOADS" ]]; then
      compadd -- ${(f)"$(cat -- "$PAYLOADS" 2>/dev/null)"}
    fi
    return
  fi

  if [[ $prev == "-f" ]]; then
    if [[ -s "$FORMATS" ]]; then
      compadd -- ${(f)"$(cat -- "$FORMATS" 2>/dev/null)"}
    fi
    return
  fi

  if [[ $prev == "--platform" ]]; then
    if [[ -s "$PLATFORMS" ]]; then
      compadd -- ${(f)"$(cat -- "$PLATFORMS" 2>/dev/null)"}
    fi
    return
  fi

  if [[ $prev == "--arch" ]]; then
    if [[ -s "$ARCHS" ]]; then
      compadd -- ${(f)"$(cat -- "$ARCHS" 2>/dev/null)"}
    fi
    return
  fi

  if [[ $prev == "-e" ]]; then
    if [[ -s "$ENCODERS" ]]; then
      compadd -- ${(f)"$(cat -- "$ENCODERS" 2>/dev/null)"}
    fi
    return
  fi

  # LHOST/LPORT suggestions and auto-equals
  if [[ "$cur" == lhost* || "$cur" == LHOST* || "$cur" == lport* || "$cur" == LPORT* ]]; then
    # add '=' as suffix and avoid a trailing space
    compadd -S '=' -- LHOST lhost LPORT lport
    compstate[insert]=''  # ensure no extra space after completion
    return
  fi

  # contextual completions if any of the flags exist anywhere on the command line
  if [[ " ${words[*]} " == *" -p "* ]]; then
    if [[ -s "$PAYLOADS" ]]; then
      compadd -- ${(f)"$(cat -- "$PAYLOADS" 2>/dev/null)"}
    fi
    return
  fi

  # default: suggest options
  if [[ -s "$OPTIONS" ]]; then
    compadd -- ${(f)"$(cat -- "$OPTIONS" 2>/dev/null)"}
  fi
}
compdef _msfvenom_completion msfvenom
EOF

chmod 644 "$INSTALL_PATH"

# init cache locally then call update
_init_cache

# try to load completion now for current zsh session if present
if [[ -n $ZSH_VERSION ]]; then
  autoload -U compinit >/dev/null 2>&1 || true
  compinit >/dev/null 2>&1 || true
  # source the new function file so it becomes active immediately
  if [[ -f "$INSTALL_PATH" ]]; then
    source "$INSTALL_PATH" >/dev/null 2>&1 || true
  fi
fi

msfupdate-completion-update() {
  echo "[*] Updating msfvenom autocomplete cache..."
  _build_cache
  echo "[+] Cache updated in $CACHE_DIR"
}

echo "[*] Installing/Updating msfvenom-completion (zsh)..."
msfupdate-completion-update
echo "[+] Installation complete. Restart your shell to enable autocomplete."
